//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkEdenNetworkSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsListInfo
    {
        public long GoodsID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Pay { get; set; }
        public string Limited { get; set; }
        public long Hour { get; set; }
        public string Race { get; set; }
        public string Sex { get; set; }
        public string Kind { get; set; }
        public short ItemClass { get; set; }
        public byte ItemType { get; set; }
        public int Grade { get; set; }
        public string OptionType { get; set; }
        public byte Num { get; set; }
        public string Img { get; set; }
        public string ShowWeb { get; set; }
        public short Recom { get; set; }
        public long HotCount { get; set; }
        public System.DateTime RegistDate { get; set; }
        public long Price { get; set; }
        public int GroupItem { get; set; }
        public short NewGoods { get; set; }
        public Nullable<short> isPromotion { get; set; }
        public Nullable<int> MaxPurchaseNum { get; set; }
    }
}
